---
# tasks file for rsyslog

# - name: "Vars | Load OS specific variables"
#   include_vars: "{{ ansible_os_family }}.yml"
#   tags: [ "rsyslog", "configuration" ]

- name: "RHEL | Packages | Include package installation tasks"
  ansible.builtin.include_tasks: rsyslog-packages-rhel.yml
  when:
    ansible_os_family == "RedHat"
  tags: ["rsyslog", "packages"]

- name: "Debian | Packages | Include package installation tasks"
  ansible.builtin.include_tasks: rsyslog-packages-deb.yml
  when:
    ansible_os_family == "Debian"
  tags: ["rsyslog", "packages"]

- name: "RHEL | Configuration | Include configuration tasks"
  ansible.builtin.include_tasks: rsyslog-config-rhel.yml
  when:
    ansible_os_family == "RedHat"
  tags: ["rsyslog", "configuration"]

- name: "Debian | Configuration | Include configuration tasks"
  ansible.builtin.include_tasks: rsyslog-config-deb.yml
  when:
    ansible_os_family == "Debian"
  tags: ["rsyslog", "configuration"]

- name: "Set rsyslog service state"
  ansible.builtin.service:
    name: "{{ rsyslog_service_name }}"
    state: "{{ rsyslog_service_state }}"
    enabled: "{{ rsyslog_service_enabled }}"
  when: rsyslog_service_name != ""
  tags: ["rsyslog", "service"]
