---
- name: Calculate serial for zone file
  ansible.builtin.include_tasks:
    file: getzoneserial.yml
  vars:
    zonefile: "{{ item.file }}"
  tags:
    - bind
    - bind-update

- name: Create zone configuration files
  ansible.builtin.template:
    src: "{{ item.file }}.j2"
    dest: "{{ bindcfgdir }}/{{ item.file }}"
    owner: root
    group: bind
    mode: '0644'
  tags:
    - bind
    - bind-update
