---
- name: Get PTR records
  ansible.builtin.include_vars: "{{ item.domain }}.yml"
  with_items:
    - "{{ reverse_zones }}"
  tags:
    - bind
    - bind-update

- name: Create backup copies of all zone files
  ansible.builtin.copy:
    src: "{{ bindcfgdir }}/{{ item.file }}"
    remote_src: true
    dest: "{{ bindcfgdir }}/{{ item.file }}.{{ ansible_date_time.iso8601_basic_short }}"
    mode: '0644'
    owner: root
    group: bind
  with_items:
    - "{{ reverse_zones }}"
    - "{{ standard_zones }}"
  tags:
    - bind
    - bind-update

- name: Update forward zone files
  ansible.builtin.include_tasks:
    file: updatezonefile.yml
  with_items:
    - "{{ standard_zones }}"
  tags:
    - bind
    - bind-update

- name: Update reverse zone files
  ansible.builtin.include_tasks:
    file: updatezonefile.yml
  with_items:
    - "{{ reverse_zones }}"
  tags:
    - bind
    - bind-update

- name: Remove old backup files
  ansible.builtin.include_tasks:
    file: delete_zone_backups.yml
  tags:
    - bind
    - bind-update
